# Generated by Django 4.2.4 on 2023-09-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0004_member_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applycrop',
            name='approved',
        ),
        migrations.AddField(
            model_name='applycrop',
            name='is_approved',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
