# Generated by Django 4.2.4 on 2023-09-14 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0005_remove_applycrop_approved_applycrop_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='applycrop',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
