# Generated by Django 4.2.4 on 2023-09-14 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0011_alter_applycrop_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applycrop',
            name='user',
            field=models.OneToOneField(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
