# Generated by Django 4.2.4 on 2023-09-15 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0014_member_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='available',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='not_available',
        ),
        migrations.AddField(
            model_name='crop',
            name='end_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='start_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
