# Generated by Django 4.2.4 on 2023-09-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0016_crop_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
