# Generated by Django 4.2.4 on 2023-09-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0018_farmerprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmerprofile',
            old_name='house_name',
            new_name='annual_income',
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='land',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
