# Generated by Django 4.2.4 on 2023-09-15 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0021_rename_phone_number_farmerprofile_contactno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmerprofile',
            old_name='wardNo',
            new_name='ward',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='contactNo',
        ),
    ]
