# Generated by Django 4.2.4 on 2023-09-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0022_rename_wardno_farmerprofile_ward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='phone_number',
            field=models.IntegerField(blank=True, max_length=12, null=True),
        ),
    ]
