# Generated by Django 4.2.4 on 2023-09-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0023_farmerprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
