# Generated by Django 4.2.4 on 2023-09-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0026_remove_farmerprofile_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='annual_income',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
