# Generated by Django 4.2.4 on 2023-09-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0027_alter_farmerprofile_annual_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='annual_income',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
