# Generated by Django 4.2.4 on 2023-09-17 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0033_rename_wardno_applycrop_ward'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applycrop',
            old_name='ward',
            new_name='wardNo',
        ),
        migrations.RemoveField(
            model_name='applycrop',
            name='file_upload',
        ),
    ]
