# Generated by Django 4.2.4 on 2023-09-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0034_rename_ward_applycrop_wardno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='end_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='start_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
