# Generated by Django 4.2.4 on 2023-09-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0036_alter_crop_end_date_alter_crop_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='end_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='start_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
