# Generated by Django 4.2.4 on 2023-09-20 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0038_alter_crop_end_date_alter_crop_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='applycrop',
            name='crop_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='ceapp.crop'),
        ),
    ]
