# Generated by Django 4.2.4 on 2023-09-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0039_applycrop_crop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='postal',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
