# Generated by Django 4.2.4 on 2023-09-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0040_alter_member_phone_alter_member_postal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='postal',
            field=models.IntegerField(),
        ),
    ]
