# Generated by Django 4.2.4 on 2023-09-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0041_alter_member_phone_alter_member_postal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applycrop',
            name='is_approved',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending'), ('waiting', 'waiting')], default='pending', max_length=10),
        ),
    ]
