# Generated by Django 4.2.4 on 2023-09-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0043_alter_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
