# Generated by Django 4.2.4 on 2023-09-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0047_rename_ward_member_wardname'),
    ]

    operations = [
        migrations.AddField(
            model_name='applycrop',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
