# Generated by Django 4.2.4 on 2023-09-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0048_applycrop_file_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
