# Generated by Django 4.2.4 on 2023-09-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0051_alter_applycrop_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='applycrop',
            name='is_approvedd',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending'), ('waiting', 'waiting')], default='pending', max_length=10),
        ),
    ]
