# Generated by Django 4.2.4 on 2023-10-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0054_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='given',
            field=models.BooleanField(default=False),
        ),
    ]
