# Generated by Django 4.2.4 on 2023-10-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0057_member_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='amob',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
