# Generated by Django 4.2.4 on 2023-10-04 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0060_member_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='date_of_birth',
            new_name='dob',
        ),
    ]
