# Generated by Django 4.2.4 on 2023-10-04 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0062_member_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
