# Generated by Django 4.2.4 on 2023-10-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0064_remove_crop_given_crop_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('meeting_time', models.TimeField(blank=True, null=True)),
                ('desmeeting', models.TextField()),
            ],
        ),
    ]
