# Generated by Django 4.2.4 on 2023-10-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0067_remove_crop_is_approved_applycrop_is_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='applycrop',
            name='crop_giventime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
