# Generated by Django 4.2.4 on 2023-10-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0068_applycrop_crop_giventime'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_mode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_venue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
