# Generated by Django 4.2.4 on 2023-10-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0069_meeting_meeting_mode_meeting_meeting_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='report',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
