# Generated by Django 4.2.4 on 2023-10-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0071_meeting_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_agenda',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
