# Generated by Django 4.2.4 on 2023-10-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0072_meeting_meeting_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
