# Generated by Django 4.2.4 on 2023-10-13 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0074_member_reset_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='attendance',
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward', models.CharField(max_length=10)),
                ('is_present', models.BooleanField(default=False)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ceapp.meeting')),
            ],
        ),
    ]
