# Generated by Django 4.2.4 on 2023-10-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0075_remove_meeting_attendance_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='is_present',
            new_name='attended',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='ward',
        ),
        migrations.AddField(
            model_name='attendance',
            name='meeting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
