# Generated by Django 4.2.4 on 2023-10-13 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0076_ward_rename_is_present_attendance_attended_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ward',
        ),
    ]
