# Generated by Django 4.2.4 on 2023-10-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0077_delete_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='ward',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
