# Generated by Django 4.2.4 on 2023-10-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0079_attendance_is_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='members_attendance',
            field=models.ManyToManyField(to='ceapp.member'),
        ),
    ]
