# Generated by Django 4.2.4 on 2023-10-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0080_meeting_members_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('annu_attendance', models.BooleanField(default=False)),
                ('anna_attendance', models.BooleanField(default=False)),
                ('arya_attendance', models.BooleanField(default=False)),
            ],
        ),
    ]
