# Generated by Django 4.2.4 on 2023-10-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0081_attendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='attendees',
            field=models.ManyToManyField(related_name='meetings', to='ceapp.attendee'),
        ),
    ]
