# Generated by Django 4.2.4 on 2023-10-13 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0082_meeting_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='members_attendance',
        ),
    ]
