# Generated by Django 4.2.4 on 2023-10-13 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0084_meeting_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='anna_attendance',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='annu_attendance',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='arya_attendance',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='name',
        ),
        migrations.AddField(
            model_name='attendee',
            name='is_present',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='attendee',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ceapp.meeting'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='ward_member',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
