# Generated by Django 4.2.4 on 2023-10-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0085_remove_attendee_anna_attendance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='ward_member',
        ),
        migrations.AlterField(
            model_name='attendee',
            name='is_present',
            field=models.CharField(choices=[('present', 'present'), ('notpresent', 'notpresent')], default='notpresent', max_length=10),
        ),
    ]
