# Generated by Django 4.2.4 on 2023-10-13 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0086_remove_attendee_meeting_remove_attendee_ward_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendee',
            name='wardno',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
