# Generated by Django 4.2.4 on 2023-10-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0088_remove_attendee_name_remove_attendee_is_present_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='anna_attendance',
            new_name='present',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='annu_attendance',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='arya_attendance',
        ),
        migrations.AddField(
            model_name='attendee',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
