# Generated by Django 4.2.4 on 2023-10-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0090_rename_present_attendee_anna_attendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WardAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_name', models.CharField(max_length=50)),
                ('is_present', models.BooleanField(default=False)),
            ],
        ),
    ]
