# Generated by Django 4.2.4 on 2023-10-14 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0092_wardattendance_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wardattendance',
            name='ward_name',
        ),
    ]
