# Generated by Django 4.2.4 on 2023-10-19 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0093_remove_wardattendance_ward_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attended',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='ward',
        ),
        migrations.AddField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
