# Generated by Django 4.2.4 on 2023-10-19 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0094_remove_attendance_attended_remove_attendance_ward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardattendance',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ceapp.meeting'),
        ),
        migrations.AlterField(
            model_name='wardattendance',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
