# Generated by Django 4.2.4 on 2023-10-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0095_wardattendance_meeting_alter_wardattendance_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardattendance',
            name='is_present',
            field=models.CharField(choices=[('absent', 'absent'), ('present', 'present'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
