# Generated by Django 4.2.4 on 2023-10-19 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0096_alter_wardattendance_is_present'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='attendees',
        ),
        migrations.DeleteModel(
            name='Attendee',
        ),
    ]
