# Generated by Django 4.2.4 on 2023-10-19 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0098_remove_wardattendance_user_wardattendance_member'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemberProfile',
            new_name='SecretaryProfile',
        ),
    ]
