# Generated by Django 4.2.4 on 2024-01-16 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0101_remove_blog_blogcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blogdes',
        ),
    ]
