# Generated by Django 4.2.4 on 2024-01-19 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0102_remove_blog_blogdes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Product',
        ),
    ]
