# Generated by Django 4.2.4 on 2024-01-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0103_rename_blog_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'FARMER'), (2, 'MEMBER'), (3, 'ADMIN'), (4, 'DRIVER')], default='1', null=True),
        ),
    ]
