# Generated by Django 4.2.4 on 2024-01-23 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0104_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(blank=True, max_length=100, null=True)),
                ('demail', models.EmailField(blank=True, max_length=100, null=True)),
                ('dage', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_set_password', models.CharField(blank=True, max_length=128, null=True)),
                ('dgender', models.CharField(blank=True, max_length=100, null=True)),
                ('daddress', models.TextField()),
                ('ddis', models.CharField(blank=True, max_length=100, null=True)),
                ('dtaluk', models.CharField(blank=True, max_length=255, null=True)),
                ('dPanchayat', models.CharField(blank=True, max_length=100, null=True)),
                ('dwardno', models.IntegerField(blank=True, max_length=100, null=True)),
                ('dpin', models.IntegerField()),
                ('dphone', models.IntegerField()),
                ('dlicense', models.CharField(blank=True, max_length=255, null=True)),
                ('ddate', models.CharField(blank=True, max_length=100, null=True)),
                ('dbio', models.TextField()),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
