# Generated by Django 4.2.4 on 2024-01-23 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0105_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='dlicense',
            new_name='dlisence',
        ),
    ]
