# Generated by Django 4.2.4 on 2024-01-23 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0106_rename_dlicense_driver_dlisence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='demail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='dname',
            new_name='name',
        ),
    ]
