# Generated by Django 4.2.4 on 2024-01-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0107_rename_demail_driver_email_rename_dname_driver_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicename', models.CharField(max_length=100)),
                ('serviceimage', models.ImageField(blank=True, null=True, upload_to='service/')),
                ('servicedes', models.TextField()),
            ],
        ),
    ]
