# Generated by Django 4.2.4 on 2024-01-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0108_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='serviceimage',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
    ]
