# Generated by Django 4.2.4 on 2024-01-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0110_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
