# Generated by Django 4.2.4 on 2024-01-31 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0111_service_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='daemail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='damob',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
