# Generated by Django 4.2.4 on 2024-01-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0112_driver_daemail_driver_damob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
            ],
        ),
    ]
