# Generated by Django 4.2.4 on 2024-02-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0116_sell_address_sell_wardno'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardattendance',
            name='meeting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
