# Generated by Django 4.2.4 on 2024-02-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0117_wardattendance_meeting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='is_accept',
            field=models.CharField(choices=[('accept', 'Accept'), ('remove', 'Remove'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
