# Generated by Django 4.2.4 on 2024-02-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0119_sell_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='applied',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
