# Generated by Django 4.2.4 on 2024-02-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0120_sell_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='crop_giventime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
