# Generated by Django 4.2.4 on 2024-02-05 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0121_sell_crop_giventime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sell',
            old_name='crop_giventime',
            new_name='giventime',
        ),
    ]
