# Generated by Django 4.2.4 on 2024-02-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0122_rename_crop_giventime_sell_giventime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardattendance',
            name='is_present',
            field=models.CharField(choices=[('absent', 'absent'), ('present', 'present')], default='present', max_length=10),
        ),
    ]
