# Generated by Django 4.2.4 on 2024-02-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0123_alter_wardattendance_is_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardattendance',
            name='is_present',
            field=models.CharField(choices=[('absent', 'absent'), ('present', 'present'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
