# Generated by Django 4.2.4 on 2024-02-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0125_alter_wardattendance_is_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='is_apply',
            field=models.CharField(choices=[('apply', 'Apply'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='sell',
            name='is_accept',
            field=models.CharField(choices=[('apply', 'Apply'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
