# Generated by Django 4.2.4 on 2024-02-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0126_sell_is_apply_alter_sell_is_accept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='is_accept',
            field=models.CharField(choices=[('accept', 'Accept'), ('remove', 'Remove'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='sell',
            name='is_apply',
            field=models.CharField(choices=[('accept', 'Accept'), ('remove', 'Remove'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
