# Generated by Django 4.2.4 on 2024-02-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0127_alter_sell_is_accept_alter_sell_is_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='is_apply',
            field=models.CharField(choices=[('apply', 'Apply'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
