# Generated by Django 4.2.4 on 2024-02-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0129_sell_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='applied_drivers',
            field=models.ManyToManyField(blank=True, related_name='applied_products', to='ceapp.driver'),
        ),
    ]
