# Generated by Django 4.2.4 on 2024-02-06 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0130_sell_applied_drivers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='is_apply',
        ),
        migrations.CreateModel(
            name='Sellapply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_apply', models.CharField(choices=[('apply', 'Apply'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ceapp.driver')),
                ('sell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ceapp.sell')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
