# Generated by Django 4.2.4 on 2024-02-06 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0131_remove_sell_is_apply_sellapply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellapply',
            name='driver',
        ),
    ]
