# Generated by Django 4.2.4 on 2024-02-06 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0133_confirm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirm',
            old_name='is_apply',
            new_name='is_confirm',
        ),
    ]
