# Generated by Django 4.2.4 on 2024-02-06 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0134_rename_is_apply_confirm_is_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellapply',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ceapp.driver'),
        ),
    ]
