# Generated by Django 4.2.4 on 2024-02-06 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0136_remove_sell_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ceapp.driver'),
        ),
    ]
