# Generated by Django 4.2.4 on 2024-02-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0137_sell_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellapply',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
