# Generated by Django 4.2.4 on 2024-02-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0139_alter_driver_dage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sellproducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('price', models.IntegerField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
