# Generated by Django 4.2.4 on 2024-02-12 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0140_sellproducts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sellproducts',
            new_name='Productcost',
        ),
    ]
