# Generated by Django 4.2.4 on 2024-02-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0141_rename_sellproducts_productcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='sell_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
