# Generated by Django 4.2.4 on 2024-02-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0142_sell_sell_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellapply',
            name='driver',
        ),
        migrations.AddField(
            model_name='sellapply',
            name='drivers',
            field=models.ManyToManyField(blank=True, to='ceapp.driver'),
        ),
    ]
