# Generated by Django 4.2.4 on 2024-02-13 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0143_remove_sellapply_driver_sellapply_drivers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellapply',
            name='drivers',
        ),
        migrations.AddField(
            model_name='sellapply',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ceapp.driver'),
        ),
    ]
