# Generated by Django 4.2.4 on 2024-02-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0144_remove_sellapply_drivers_sellapply_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellapply',
            name='total_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
