# Generated by Django 4.2.4 on 2024-02-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0145_sellapply_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellapply',
            name='is_collected',
            field=models.BooleanField(default=False),
        ),
    ]
