# Generated by Django 4.2.4 on 2024-02-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0146_sellapply_is_collected'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellapply',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
    ]
