# Generated by Django 4.2.4 on 2024-02-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0147_sellapply_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellapply',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
