# Generated by Django 4.2.4 on 2024-02-23 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0148_alter_sellapply_is_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellapply',
            old_name='is_paid',
            new_name='is_paidd',
        ),
    ]
