# Generated by Django 4.2.4 on 2024-02-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0149_rename_is_paid_sellapply_is_paidd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellapply',
            name='is_paidd',
            field=models.BooleanField(default=True),
        ),
    ]
