# Generated by Django 4.2.4 on 2024-02-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0152_alter_sellapply_is_paidd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellapply',
            name='is_paidd',
        ),
        migrations.AddField(
            model_name='sellapply',
            name='is_amount',
            field=models.BooleanField(default=False),
        ),
    ]
