# Generated by Django 4.2.4 on 2024-02-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0153_remove_sellapply_is_paidd_sellapply_is_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
