# Generated by Django 4.2.4 on 2024-02-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0154_farmerprofile_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellapply',
            name='paid_amount',
            field=models.IntegerField(default=0),
        ),
    ]
