# Generated by Django 4.2.4 on 2024-02-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0155_sellapply_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='dvehicle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='dvehicletype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
