# Generated by Django 4.2.4 on 2024-02-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0157_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellapply',
            name='is_confirm',
            field=models.CharField(choices=[('confirm', 'Confirm'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
