# Generated by Django 4.2.4 on 2024-03-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0158_sellapply_is_confirm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mleave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('meeting_time', models.TimeField(blank=True, null=True)),
                ('meeting_venue', models.CharField(blank=True, max_length=100, null=True)),
                ('reason', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
