# Generated by Django 4.2.4 on 2024-03-02 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0160_remove_mleave_meeting_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wardattendance',
            name='meeting_date',
        ),
    ]
