# Generated by Django 4.2.4 on 2024-03-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0161_remove_wardattendance_meeting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardattendance',
            name='reason',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
