# Generated by Django 4.2.4 on 2024-03-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0162_wardattendance_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardattendance',
            name='meeting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
