# Generated by Django 4.2.4 on 2024-03-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0163_wardattendance_meeting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardattendance',
            name='leave_applied',
            field=models.BooleanField(default=False),
        ),
    ]
