# Generated by Django 4.2.4 on 2024-03-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0164_wardattendance_leave_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardattendance',
            name='is_grant',
            field=models.CharField(choices=[('pending', 'pending'), ('grant', 'grant')], default='pending', max_length=10),
        ),
    ]
