# Generated by Django 4.2.4 on 2024-03-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0165_wardattendance_is_grant'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellapply',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
