# Generated by Django 4.2.4 on 2024-03-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0168_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='farmerName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
