# Generated by Django 4.2.4 on 2024-03-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0170_remove_total_sell_remove_total_sellapply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
