# Generated by Django 4.2.4 on 2024-03-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0171_total_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
