# Generated by Django 4.2.4 on 2024-03-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0173_machinery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinery',
            name='count',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
