# Generated by Django 4.2.4 on 2024-03-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0174_alter_machinery_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinery',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productcost',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
