# Generated by Django 4.2.4 on 2024-03-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0175_machinery_is_active_productcost_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinery',
            name='days',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
