# Generated by Django 4.2.4 on 2024-03-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0178_machinery_apply_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinery',
            name='farmerName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
