# Generated by Django 4.2.4 on 2024-03-06 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0179_machinery_farmername'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinery',
            name='applied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applied_machines', to='ceapp.farmerprofile'),
        ),
    ]
