# Generated by Django 4.2.4 on 2024-03-06 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0182_remove_machineryapply_applied_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinery',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
