# Generated by Django 4.2.4 on 2024-03-06 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0183_machinery_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationMachinery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_date', models.DateField(blank=True, null=True)),
                ('farmer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('applied_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ceapp.farmerprofile')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_applications', to='ceapp.machinery')),
            ],
        ),
    ]
