# Generated by Django 4.2.4 on 2024-03-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0184_applicationmachinery'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmachinery',
            name='available',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
