# Generated by Django 4.2.4 on 2024-03-07 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0187_remove_machinery_applied_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationmachinery',
            name='machine',
        ),
    ]
