# Generated by Django 4.2.4 on 2024-03-07 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0188_remove_applicationmachinery_machine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MachineryApply',
        ),
    ]
