# Generated by Django 4.2.4 on 2024-03-07 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0190_remove_machinery_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationmachinery',
            name='applied_by',
        ),
        migrations.DeleteModel(
            name='Machinery',
        ),
        migrations.DeleteModel(
            name='ApplicationMachinery',
        ),
    ]
