# Generated by Django 4.2.4 on 2024-03-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0192_addmachinery'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmachinery',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
