# Generated by Django 4.2.4 on 2024-03-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0193_addmachinery_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmachinery',
            name='apply_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
