# Generated by Django 4.2.4 on 2024-03-07 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0195_addmachinery_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmachinery',
            name='farmer_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ceapp.farmerprofile'),
        ),
    ]
