# Generated by Django 4.2.4 on 2024-03-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0196_addmachinery_farmer_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmachinery',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addmachinery',
            name='farmerName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addmachinery',
            name='wardNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
