# Generated by Django 4.2.4 on 2024-03-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0197_addmachinery_address_addmachinery_farmername_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmachinery',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
