# Generated by Django 4.2.4 on 2024-03-08 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0198_alter_addmachinery_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineryApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmerName', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('wardNo', models.CharField(blank=True, max_length=100, null=True)),
                ('farmer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ceapp.farmerprofile')),
                ('machinery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ceapp.addmachinery')),
            ],
        ),
    ]
