# Generated by Django 4.2.4 on 2024-03-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0199_machineryapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineryapplication',
            name='apply_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
