# Generated by Django 4.2.4 on 2024-03-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0200_machineryapplication_apply_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineryapplication',
            name='total_days',
            field=models.DateField(blank=True, null=True),
        ),
    ]
