# Generated by Django 4.2.4 on 2024-03-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0202_alter_machineryapplication_machinery'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineryapplication',
            name='acount',
            field=models.IntegerField(default=0),
        ),
    ]
