# Generated by Django 4.2.4 on 2024-03-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0203_machineryapplication_acount'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineryapplication',
            name='Tcount',
            field=models.IntegerField(default=0),
        ),
    ]
