# Generated by Django 4.2.4 on 2024-03-12 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0205_machineryapplication_file_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineryapplication',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ceapp.member'),
        ),
    ]
