# Generated by Django 4.2.4 on 2024-03-13 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0206_machineryapplication_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineryTcount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acount', models.IntegerField(default=0)),
                ('Tcount', models.IntegerField(default=0)),
                ('machinery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ceapp.addmachinery')),
            ],
        ),
    ]
