# Generated by Django 4.2.4 on 2024-03-14 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0207_machinerytcount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machinerytcount',
            old_name='acount',
            new_name='count',
        ),
        migrations.RemoveField(
            model_name='machinerytcount',
            name='Tcount',
        ),
        migrations.RemoveField(
            model_name='machinerytcount',
            name='machinery',
        ),
    ]
