# Generated by Django 4.2.4 on 2024-03-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0208_rename_acount_machinerytcount_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineryapplication',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
