# Generated by Django 4.2.4 on 2024-03-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0211_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellapply',
            name='total_amount_new',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
