# Generated by Django 4.2.4 on 2024-03-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0212_sellapply_total_amount_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellapply',
            name='total_amount_new',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
