# Generated by Django 4.2.4 on 2024-03-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0214_alter_total_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='total_amount_new',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
