# Generated by Django 4.2.4 on 2024-03-30 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0219_total_amount_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='sellapply',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ceapp.sellapply'),
        ),
    ]
